---
TemplateConfig:
  DependsOn:
  - ConfigRuleCloudformationDriftRoles
  Capabilities:
  - CAPABILITY_NAMED_IAM
  Role: ConfigRuleCloudformationDriftRole
  DeployTo:
    Regions:
    - AllRegions
    Accounts:
    - NotMainAccount
